spring:
#mongo配置
  data:
    mongodb:
      database: MyFirstdb
      uri: mongodb://127.0.0.1:27017
#数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiroDemo
    username: root
    password: root
  # 配置初始化大小、最小、最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
  # 配置获取连接等待超时的时间
    maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  # 配置监控统计拦截的filters
    filters: stat
#Redis
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000
    database: 0
debug: true
